# Generated by Django 5.1.2 on 2024-12-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.IntegerField()),
                ('id_reloj', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('precio_de_venta', models.IntegerField()),
                ('forma_de_pago', models.CharField(max_length=255)),
                ('estado_de_entrega', models.CharField(max_length=255)),
            ],
        ),
    ]
