# Generated by Django 5.1.2 on 2024-12-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0002_alter_venta_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_empleado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
