# Generated by Django 5.1.2 on 2024-12-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.IntegerField()),
                ('id_reloj', models.IntegerField()),
                ('descripcion_problema', models.TextField(max_length=255)),
                ('costo_de_reparacion', models.IntegerField()),
                ('tiempo_de_reparacion', models.CharField(max_length=30)),
                ('estado_reparación', models.CharField(max_length=255)),
            ],
        ),
    ]
