# Generated by Django 5.1.2 on 2024-12-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparacion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='idreparacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
