# Generated by Django 5.1.2 on 2024-12-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparacion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
