# Generated by Django 5.1.2 on 2024-12-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reloj',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('anio_de_lanzamiento', models.IntegerField()),
                ('idproveedor', models.IntegerField()),
            ],
        ),
    ]
